### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by synw** [k-pramod/channel.js#1]
I followed your tutorial and got this error when the pages load:

_ReferenceError: exports is not defined_

Refering to line 128 of the channels.js file

**Comment by p13i** [comment]
@synw : Thanks for checking out this project! I've updated the code so that this error no longer arises.

Check out the updated ['Getting Started'](https://github.com/k-pramod/channel.js/blob/v0.1.0/docs/channel.md#getting-started) with the correct `.js` files that you can include in your own projects. I've also updated the [example app](https://github.com/k-pramod/channel.js/tree/v0.1.0/examples/chatter) so you can tinker with a [functional front-end channel.js app](https://github.com/k-pramod/channel.js/blob/v0.1.0/examples/chatter/chat/static/js/chat.js).

Let me know if you have any other concerns!
