### ISSUE TITLE
Example does not work in python 2.7

### ISSUE THREAD

**Issue by synw** [k-pramod/channel.js#3]
I tried your updated example but had to change the function declarations to make it work with python 2.7: https://github.com/synw/channel.js/compare

**Comment by p13i** [comment]
Good catch! I've updated the project to have Python 2.7 support. You shouldn't have any issues running the example now.

Also, I've refactored the 'chatter' example so that new events can be registered in the [`event_routing`](https://github.com/k-pramod/channel.js/blob/master/examples/chatter/chat/routing.py#L8) list just like with Django's `urlpatterns`. Now, new events can be registered in `event_routing` and implemented in [`consumers/base.py`](https://github.com/k-pramod/channel.js/blob/master/examples/chatter/chat/consumers/events.py).
